export const themes = {
  grass: {
    name: 'Grass',
    bombIcon: '💣',
    flagIcon: '🚩',
    tileBg: '#a8d5a2',
    tileRevealedBg: '#e6f3e6',
    textColor: '#4a5a2f',
    buttonBg: '#a0d4a0',
    buttonText: '#4a5a2f',
  },
  ocean: {
    name: 'Ocean',
    bombIcon: '🐚',
    flagIcon: '⚓',
    tileBg: '#a0ced9',
    tileRevealedBg: '#d4f1f9',
    textColor: '#0b3d91',
    buttonBg: '#99d0d3',
    buttonText: '#0b3d91',
  },
  fire: {
    name: 'Fire',
    bombIcon: '🔥',
    flagIcon: '☢️',
    tileBg: '#f4b183',
    tileRevealedBg: '#fde0c3',
    textColor: '#7a1900',
    buttonBg: '#f3aa7c',
    buttonText: '#7a1900',
  },
};